// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJJavWdK7dN8wD938akCGZWwZunSVPZjs',
    appId: '1:40200039898:web:beaefc07f2b60fff16a4e3',
    messagingSenderId: '40200039898',
    projectId: 'wound-monitoring-a4f33',
    authDomain: 'wound-monitoring-a4f33.firebaseapp.com',
    storageBucket: 'wound-monitoring-a4f33.firebasestorage.app',
    measurementId: 'G-5VFER6N524',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzobR3QQMb-6iGNQcctxSG8gK-AYn_nOo',
    appId: '1:40200039898:android:e1fa6e005051856016a4e3',
    messagingSenderId: '40200039898',
    projectId: 'wound-monitoring-a4f33',
    storageBucket: 'wound-monitoring-a4f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkQTFrUsIOW7rkfmVNCAxfNB7TmH8zpOE',
    appId: '1:40200039898:ios:2d806e3e7cea660916a4e3',
    messagingSenderId: '40200039898',
    projectId: 'wound-monitoring-a4f33',
    storageBucket: 'wound-monitoring-a4f33.firebasestorage.app',
    iosBundleId: 'com.example.woundMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkQTFrUsIOW7rkfmVNCAxfNB7TmH8zpOE',
    appId: '1:40200039898:ios:2d806e3e7cea660916a4e3',
    messagingSenderId: '40200039898',
    projectId: 'wound-monitoring-a4f33',
    storageBucket: 'wound-monitoring-a4f33.firebasestorage.app',
    iosBundleId: 'com.example.woundMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJJavWdK7dN8wD938akCGZWwZunSVPZjs',
    appId: '1:40200039898:web:73e254a529c7153e16a4e3',
    messagingSenderId: '40200039898',
    projectId: 'wound-monitoring-a4f33',
    authDomain: 'wound-monitoring-a4f33.firebaseapp.com',
    storageBucket: 'wound-monitoring-a4f33.firebasestorage.app',
    measurementId: 'G-LWM57K37V9',
  );
}
